* <<<CP1222>>> ADVANCED DATABASES 
:properties:
:author: J. Suresh, A. Beulah
:date: 9 May 2022
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
The student should be made to:
- Understand the concepts of distributed databases
- Be familiar with the data models for data lake.
- Learn the basics of columnar and key-value databases.
- Be exposed to document and graph databases.
- Gain knowledge about streaming data.


{{{unit}}}
|Unit I |Distributed Databases|9| 	
Distribution Models: Single Server-- Sharding-- Master--Slave Replication --Peer-to-Peer Replication -- Combining Sharding and Replication; Consistency:  Update Consistency-- Read Consistency-- Relaxing Consistency--The CAP Theorem-- Relaxing Durability-- Quorums.

{{{unit}}}
|Unit II|Data Models for Data Lake|9|
Data Models -- Categorizing Data Models -- Data Model vs Data Format -- Data Stream -- Understanding Data Lake -- Inside Data Lake -- Generic Structure of Data Ponds -- Applications of Data Pond – Data Warehousing vs Data Lake -- Big Data Integration with Data Lake -- Apache Sqoop.

{{{unit}}}
|Unit III|Columnar and Key-Value Databases |9| 
Cassandra Data Model  -- Clusters -- Keyspaces --Column Families --Columns -- Super Columns -- Design Differences Between RDBMS and Cassandra --Design Patterns -– Cassandra Architecture; Key-Value Databases: What Is a Key-Value Store --Key Value Store Features -- Use Cases.

{{{unit}}}
|Unit IV|Document and Graph Databases |9| 
Database for modern Web: MongoDB -- MongoDB Shell -- Creating, Updating, and Deleting Documents -- Querying; Graph Databases An Overview -- Started with Neo4j -- Modelling data for Neo4j -- Use Case Examples: Recommender Systems & Impact Analysis and Simulation --Visualization for Neo4j.

{{{unit}}}
|Unit V|Streaming Data|9| 
Change Data Capture Concepts --Strategies for Data Capture -- Types of CDC -- CDC Trade-offs --CDC Tools -- Analyzing a Centralized Data Store -- Publishing to Kafka -- Schema and Data.

\hfill *Total: 45*

** Course Outcomes
After the completion of this course, students will be able to: 
- Make use of the methods and techniques for distributed quey processing(k3)
- Explain the data models for data lake. (K2)
- Apply the techniques of wide-column and key-value databases to create databases and run the queries. (K3)
- Apply the concepts of document and graph databases to add contents and run the queries. (K3)
- Explain the concepts of streaming data (K2)


      
** References
1. R. Elmasri, S.B. Navathe,``Fundamentals of Database Systems'',
   Sixth Edition, Pearson Education/Addison Wesley, 2010. (Units I,
   II, III, V)
2. Vijay Kumar, ``Mobile Database Systems'', John Wiley &
   Sons, 2006. (Unit IV)
3. Henry F Korth, Abraham Silberschatz, S. Sudharshan,``Database
   System Concepts'', Sixth Edition, McGraw Hill, 2011.
4. C. J. Date, A.Kannan, S.Swamynathan, ``An Introduction to Database
   Systems'', Eighth Edition, Pearson Education, 2006.
5. Carlo Zaniolo, Stefano Ceri, Christos Faloutsos, Richard
   T.Snodgrass, V.S.Subrahmanian, Roberto Zicari, ``Advanced Database
   Systems'', Morgan Kaufmann publishers, 2006.
