*
:properties:
:author: Kanchana
:date: 
:end:



#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To understand foundations of cognitive computing
- To explore the role of AI, Big Data, Machine learning, NLP in cognitive systems
- To understand the business implications of cognitive computing and develop solutions.


{{{unit}}}
| UNIT I | FOUNDATION OF COGNITIVE COMPUTING | 8 |
Cognitive computing as a new generation -- the uses of cognitive systems -- system cognitive, gaining insights from data -- Artificial Intelligence as the foundation of cognitive computing, understanding cognition; Design Principles for Cognitive Systems: Components of a cognitive system, building the corpus -- bringing data into cognitive system -- machine learning -- hypotheses generation and scoring -- presentation and visualization services.

{{{unit}}}
| UNIT II | NLP IN SUPPORT OF A COGNITIVE SYSTEM | 8 |
Role of NLP in a cognitive system -- semantic web -- Applying Natural language technologies to Business problems; Representing knowledge in Taxonomies and Ontologies: Representing knowledge -- Defining Taxonomies and Ontologies --  Knowledge representation -- Models for knowledge representation -- Implementation considerations.  

{{{unit}}}
| UNIT III | RELATIONSHIP BETWEEN BIG DATA AND COGNITIVE COMPUTING | 8 |
Dealing with human-generated data -- defining big data -- architectural foundation -- analytical data warehouses; Hadoop -- data in motion and streaming data; integration of big data with traditional data; Applying Advanced Analytics to cognitive computing: Advanced analytics is on a path to cognitive computing -- Key capabilities in advanced analytics -- Using advanced analytics to create value -- Impact of open source tools on advanced analytics. 

{{{unit}}}
| UNIT IV | BUSINESS IMPLICATIONS OF COGNITIVE COMPUTING  | 8 |
Preparing for change -- advantages of new disruptive models --  knowledge meaning to business, difference with a cognitive systems approach -- meshing data together differently -- using business knowledge to plan for the future --  answering business questions in new ways , building business specific solutions; The process of building a cognitive application: Emerging cognitive platform, defining the objective and the domain -- understanding the intended users and their attributes -- questions and exploring insights -- training and testing .

{{{unit}}}
| UNIT V | BUILDING A COGNITIVE HEALTH CARE APPLICATION | 8 |
Foundations of cognitive computing for healthcare -- constituents in healthcare ecosystem -- learning from patterns in healthcare Data -- cognitive applications across the health care eco system -- cognitive application for healthcare -- using cognitive applications to improve health and wellness, to enhance the electronic medical record, to improve clinical teaching; Smarter cities: Cognitive Computing in Government -- smarter approaches to preventative healthcare, building a smarter transportation infrastructure --  creating a cognitive community infrastructure -- next phase of cognitive cities 


\hfill *Total Periods: 45*


** COURSE OUTCOMES
Upon completion of this course, the students should be able to:
-	Identify how Artificial Intelligence, Machine Learning and Cognitive Computing are related together and are used for application development (K2)
-	Describe Cognitive computing and NLP based techniques and models (K2)
-	Apply advanced analytics to cognitive computing (K3)
-	Apply technical and managerial issues in developing applications based on cognitive computing and Artificial Intelligence Applications techniques. (K3)
- Apply and assess cognitive computing and Artificial Intelligence Applications in an organizational setting (K3)



** REFERENCES
1. Judith H Hurwitz, Marcia Kaufman, Adrian Bowles , “Cognitive computing and Big Data Analytics” , Wiley, 2015
2. Pradeep Kumar Mallick, Samarjeet Borah, Emerging Trends and Applications in Cognitive Computing, IGI Global, 2018
3. Vishal Jain, Akash Tayal, Jaspreet Singh, Cognitive Computing Systems - Applications and Technological Advancements, Taylor & Francis, 2021 
4. Rob High , Tanmay Bakshi, Cognitive Computing with IBM Watson, Packt, 2019


#+begin_comment

   ** CO TO PO/PSO MAPPING

|  | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 |PSO1 | PSO2 |PSO3 |
|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| CO1    | 2 | 1 |   |   |   |   |   |   |   |    |    |    | 1 |   |   |
| CO2    | 3 | 2 |   |   |   |   |   |   |   |    |    |    | 2 |   |   |
| CO3    | 3 |   |   |   |   |   |   |   |   |    |    |    | 2 |   |   |
| CO4    | 3 | 2 |   |   |   |   |   |   |   |    |    |    | 2 |   |   |
| CO5    | 3 | 2 | 2 |   | 2 |   |   |   |   |    |    |    | 2 |   |   |

|--------+---+---+---+---+---+---+---+---+---+----+----+----+---+---+---|
| Course | 3 | 2 | 2 |   | 2 |   |   |   |   |    |    |    | 2 |   |   |
#+TBLFM: @>$INVALID..$15='(ceiling (/ (+ @2..@7) 6));N

# | Score|14 | 7 | 2 |   | 2 |   |   |   |   |    |    |    | 9 |   |   |



#+end_comment
