* <<<CP1325>>> DATA VISUALIZATION TECHNIQUES 
:properties:
:author: M Saritha
:date: 05 May 2022
:end:

#+startup: showall

{{{credits}}}
|L|T|P|C|
|3|0|0|3|

** Course Objectives
- To introduce visual perception and core skills for visual analysis.
- To visualize time-series, part-to-whole and ranking Analysis patterns.
- To analyze the deviation and distribution of data in real time. 
- To analyze correlation and multivariate patterns of data. 
- To understand issues and best practices in information dashboard design. 

|Unit I| Building Core Skills for Visual Analysis|9| 
Information Visualization -- Prerequisites for Enlightening Analysis: Aptitudes and attitudes of effective Analysts -- Traits of meaningful data; Power of Visual Perception -- How Visual Perception Works -- Making Abstract Data Visible -- Analytical Interaction -- Analytical Navigation -- Optimal Quantitative Scales -- Reference Lines and Regions -- Trellises and Crosstabs -- Multiple Concurrent Views -- Focus and Context -- Details on Demand -- Over-plotting reduction -- Analytical Patterns: Pattern examples
|Unit II| Time-Series Analysis, Part-to-whole and Ranking Analysis|9| 
Time-series Analysis: Introduction -- Time-series patterns -- Time-series displays -- Time-series analysis techniques and best practices; Part-to-whole and Ranking Analysis: Introduction -- Part-to-whole and ranking patterns -- Part-to-whole and ranking displays -- Part-to-whole and ranking techniques and best practices
|Unit III| Deviation Analysis and Distribution Analysis|9| 
Deviation Analysis: Introduction -- Deviation analysis displays -- Deviation analysis techniques and best practices; Distribution Analysis: Introduction -- Describing distributions – Distribution patterns -- Distribution displays -- Distribution analysis techniques and best practices; 

|Unit IV| Correlation Analysis and Multivariate Analysis|9| 
Correlation Analysis: Introduction -- Describing correlations -- Correlation patterns -- Correlation displays -- Correlation analysis techniques and best practices; Multivariate Analysis: Introduction -- Multivariate patterns -- Multivariate displays -- Multivariate analysis techniques and best practices

|Unit V| Information Dashboard Design|9| 
Information Dashboard: Clarifying the vision -- Thirteen common mistakes in dashboard design -- Tapping into the power of visual perception -- Eloquence through simplicity -- Effective dashboard display media -- Putting it all together


\hfill *Total: 45*

** Course Outcomes
After the completion of this course, students will be able to: 
- Recognize core skills for visual analysis (K2)
- Apply visualization techniques for various data analysis tasks (K3)
- Employ information dashboard design techniques (K3)
- Use different tools to better visualize data (K3)
      
** Text Books
1. Stephen Few, ``Now you see it: Simple Visualization techniques for quantitative analysis'', Analytics Press, 2009. (Units I, II, III, IV)
2. Stephen Few, ``Information dashboard design: Displaying data for at-a-glance monitoring'', second edition, Analytics
   Press, 2013. (Unit V)
** References
1. Ben Fry, ``Visualizing data: Exploring and explaining data with the processing environment'', O'Reilly, 2008.
2. Edward R. Tufte, ``The visual display of quantitative information'', Second Edition, Graphics Press, 2001.
3. Nathan Yau, ``Data Points: Visualization that means something'', Wiley, 2013.
4. Tamara Munzner, ``Visualization Analysis and Design'', AK Peters Visualization Series, CRC Press, Nov. 2014
