* <<<CP1323>>> COMPUTER VISION
:properties:
:author: S. Manisha
:date: 06 May 2022
:end:

#+startup: showall

{{{credits}}}
|L|T|P|C|
|3|0|0|3|

** Course Objectives
- To review image processing techniques for computer vision.
- To understand shape and region analysis.
- To understand Hough Transform and its applications to detect lines, circles, ellipses.
- To understand three-dimensional image and motion analysis techniques.
- To study some applications of computer vision algorithms.


{{{unit}}}
|Unit I |Image Processing Foundations	|9| 
Review of Image Processing Techniques: Segmentation: Edge detection techniques --
Corner and interest point detection; Mathematical morphology; Texture; Binary Shape Analysis; Boundary Tracking Procedures

{{{unit}}}
|Unit II|Boundary and Region Descriptors and Hough Transform|9| 
Boundary Descriptors: Chain codes; Fourier Descriptors; Region Descriptors;
Moments; Line Detection: Hough Transform (HT) for line detection -- RANSAC for
straight line detection; HT based circular object detection; HT based
ellipse detection

{{{unit}}}
|Unit III|3D Vision and Motion|9| 
Methods for 3D vision: Projection schemes -- Shape from shading --
Photometric stereo -- Shape from texture -- Shape from focus -- Active
range finding; Surface Representations; Point-based Representations;
Volumetric Representations; Introduction to Motion: Triangulation -- Bundle adjustment --
Translational alignment -- Parametric motion -- Spline-based motion --
Optical flow -- Layered motion


{{{unit}}}
|Unit IV|Image Registration and Transformation|9| 
 Image Registration: Preprocessing -- Feature
selection -- Feature correspondence -- Transformation functions; Camera Calibration -- Intrinsic and Extrinsinc Parameters -- Correcting for Radial Distotrions -- Multiple view vision -- generalized epipolar geometry -- Essential Matrix -- fundamental matrix -- image rectification -- 3D reconstruction 


{{{unit}}}
|Unit V|Vision Applications |9|
 Application: Photo album -- Face
detection -- Face recognition -- Eigen faces -- Active appearance and
3D shape models of faces; Application: Surveillance -- Foreground -
background separation -- Particle filters -- Chamfer matching --
Tracking and occlusion -- Combining views from multiple cameras --
Human gait analysis; Application: In -vehicle vision system --
locating roadway -- road markings -- identifying road signs --
locating pedestrians.


\hfill *Total: 45*

** Course Outcomes
After the completion of this course, students will be able to: 

- Apply fundamental image processing techniques required for computer vision. (K3)
- Apply boundary and region descriptors and hough transforms. (K3)
- Apply 3D vision techniques. (K3)
- Apply image registration and transormation of image and perform camera calibration (K3)
- Analyze the application and develop applications using computer vision techniques. (K4)

  
** References
1. E. R. Davies, ―Computer & Machine Vision‖, Fifth Edition, Academic Press, 2017.  (Units 1 to 5)
2. D. L. Baggio et al., ―Mastering OpenCV with Practical Computer Vision Projects‖, Packt Publishing, 2012.
3. Jan Erik Solem, ―Programming Computer Vision with Python: Tools and algorithms for analyzing images‖, O'Reilly Media, 2012. 
4. Mark Nixon and Alberto S. Aquado, ―Feature Extraction & Image Processing for Computer Vision‖, Third Edition, Academic Press, 2012. 
5. R. Szeliski, ―Computer Vision: Algorithms and Applications‖, Second edition, Springer 2022. 
6. Simon J. D. Prince, ―Computer Vision: Models, Learning, and Inference‖, Cambridge University Press, 2012.
